### ISSUE TITLE
Not working from Package Manager

### ISSUE THREAD

**Issue by bobell** [ThomasKliszowski/json_reindent#10]
Can't run on ST2 v2.0.2 build 2221 on MacBook OSX 10.10.5 Maybe you are no longer supporting this?

I install Json-Reindent v.2.0.1 via Package Control like normal (Package Control: Install Package). Quit and restart ST2. "Package Control: List Packages" shows it is there. 

![screenshot 2016-12-22 12 14 56](https://cloud.githubusercontent.com/assets/12239715/21434038/60ff5626-c840-11e6-945c-47fc0749de6f.png)

However no commands are available in Package Control.

![screenshot 2016-12-22 12 15 30](https://cloud.githubusercontent.com/assets/12239715/21434045/676e64ac-c840-11e6-9ed8-3a5bd1dfff7a.png)

**Comment by dmohnen** [comment]
I have this same issue

**Comment by ThomasKliszowski** [comment]
It seems that the relative import does not work anymore. 
I will fix this soon.

**Comment by ThomasKliszowski** [comment]
Fixed in 2.0.4.
