### ISSUE TITLE
show errors in statusbar.

### ISSUE THREAD

**Issue by ctf0** [ThomasKliszowski/json_reindent#3]
is there away to show the error that stopped the plugin from running in the status bar ,instead of having to guess if there was a problem or not ?

also having any comments in the json file makes the plugin stop working.

**Comment by ThomasKliszowski** [comment]
Actually, plugin errors are shown into the Sublime Text Console.

Unfortunately, the plugin does not work at this time when you add any comments. I directly use the Python `json` module to do the job. Note that comments are not valid in JSON: http://stackoverflow.com/questions/244777/can-i-comment-a-json-file. This is why it does not work with this module.

**Comment by ctf0** [comment]
ah bolx ,thanx for the tip thought :).
