### ISSUE TITLE
Problem with Unicode?

### ISSUE THREAD

**Issue by rportugal** [ThomasKliszowski/json_reindent#4]
Starting with the JSON:
```json
{ "something": [ { "stuff": "Καλημέρα" } ] }
```

After running JSON reindent, it becomes:
```json
{
   "something": [
      {
         "stuff": "\u039a\u03b1\u03bb\u03b7\u03bc\u03ad\u03c1\u03b1"
      }
   ]
}
```

I believe it shouldn't perform this conversion?
Thanks.

**Comment by ThomasKliszowski** [comment]
`view.replace` seems to support unicode as string parameter, I don't see any problem with this merge request.

Thanks for your help!
