### ISSUE TITLE
error on last comma

### ISSUE THREAD

**Issue by ctf0** [ThomasKliszowski/json_reindent#6]
hi again, am currently having an issue when there is a comma before the close of the brace like so
```json
{
"x":true,
"y":false, // < note the comma
}
```
so i was thinking instead of just giving an error, is there any chance for the plugin to remove the last comma ?

**Comment by ThomasKliszowski** [comment]
Hi,

I fixed that by using the PyYAML parser instead of the JSON one.
You can try it in the new 2.0.0 version.

**Comment by ctf0** [comment]
perfect, thanx :+1:
