### ISSUE TITLE
Failing on escaped characters

### ISSUE THREAD

**Issue by winternet-studio** [ThomasKliszowski/json_reindent#7]
When to try to reindent the following string nothing happens (no errors, no nothing):

{"deviceID":"99d5ce418b134705","_useragent":"android\/app\/4.4"}

If I remove the escaped slashes it works just fine.

Using Sublime 3.

**Comment by ThomasKliszowski** [comment]
Sorry for the delay, I fix this issue on December, 23rd 2015 by falling back to the JSON parse if the YAML one fails: 01c78785bf6c5618fd68d693a31faf1492e78f92
