### ISSUE TITLE
bad comments indentation

### ISSUE THREAD

**Issue by ctf0** [ThomasKliszowski/json_reindent#8]
i have something like  `"on_pre_save_language": [{"command": "sublime_json_reindent"}]`

when i comment the command line it become
`"// \"command\"": "sublime_json_reindent"`

**Comment by ThomasKliszowski** [comment]
Actually, comments are not supported according to the JSON spec.
I introduced a side effect by using the Yaml parser instead of the JSON one. Maybe I can find a fix for that.

**Comment by ctf0** [comment]
:metal:
