### ISSUE TITLE
Integer as Key is cast String

### ISSUE THREAD

**Issue by wfleurant** [ThomasKliszowski/json_reindent#9]
This is seen when formatting / reindenting a (valid) Python Dictionary (not JSON) which may be confusing.

```
{'1001': 'ThomasKliszowski/json_reindent', 1001: 'ThomasKliszowski/json_reindent'}
```
output

```
{
    "1001": "ThomasKliszowski/json_reindent",
    "1001": "ThomasKliszowski/json_reindent"
}
```

expected output
```
{
    "1001": "ThomasKliszowski/json_reindent",
    1001: "ThomasKliszowski/json_reindent"
}
```

that's all -- been using this for some time now, great contribution to ST,
thanks.

**Comment by ThomasKliszowski** [comment]
Thanks for paying attention to this plugin.
Unfortunately, a key can't be an integer according to the JSON specifications: http://www.json.org/
This is why the Python JSON library converts your integer to a string.

I know that can be confusing.

Maybe we can do something by detecting that your file is a Python file and not a Javascript / JSON one... But it is not a clean way to do this in my opinion, too hackish. And obviously, the result will not be a valid JSON, which can be confusing regarding the plugin name.

**Comment by wfleurant** [comment]
I'm in agreement, no doubt.
-w
